# Macro file for N1
#

##################### G4State_PreInit ###################

# ================== Analysis settings ==================

# Analysis parameters
/analysis/setFileName data/PPD1
/analysis/setActivation false

# Switch on/off histos
/analysis/setHistoDirName histograms
/analysis/h1/setActivationToAll true

# Switch on/off ntupling
/analysis/setNtupleDirName ntuples
/analysis/ntuple/setActivationToAll true

# =================== Physics settings ==================

/process/em/fluo true
/process/em/auger true
/process/em/augerCascade true
/process/em/deexcitationIgnoreCut true 
/process/em/lowestElectronEnergy 0 keV
#/process/em/AddDNARegion Target DNA_Opt0
/process/em/printParameters

# Change the default number of threads (in multi-threaded mode)
/run/numberOfThreads 8

################## Kernel initialization ################

/run/initialize

#####################  G4State_Idle #####################

# ================== Verbose settings ===================

/control/verbose 0
/process/verbose 0
/run/verbose 0
/event/verbose 0
/tracking/verbose 0

# ================== Cutoff settings ===================

/run/setCut 1 mm
/run/setCutForRegion Target 10 um

# ==================== Phantom settings =================

# Set concentration
#/PDD1/geometry/SetConcentration 0 mg/g
/material/g4/printMaterial

# ==================== Beam settings ====================

# Conical beam
#/control/execute beam/conical-beam.mac

# Eliptical beam
/control/execute beam/elliptical-beam.mac
/gps/pos/halfx 0 mm
/gps/pos/halfy 0 mm

####################### Neutron beam ####################

# Fast Neutron Beam
#/gps/particle neutron

# Beam fast neutron spectrum
#/control/execute beam/fast-neutron.mac

# Beam thermal neutron spectrum
#/control/execute beam/thermal-neutron.mac

######################## Proton beam ####################

# Mono Proton Beam
/gps/particle proton

# Beam spectrum
/gps/ene/type Gauss
/gps/energy 150. MeV
/gps/ene/sigma 2 MeV
#/gps/ene/mono 160 MeV

###################### Carbon ion beam ##################

# Mono carbon ion beam
#/gps/particle ion
#/gps/ion 6 12

# Beam spectrum
#/gps/ene/type Gauss
# Kinetic Energy.
# 195.MeV/u * 12(AtomicMass) = 2340. MeV
#/gps/energy 2340. MeV
#/gps/ene/sigma 20 MeV
#/gps/ene/mono 2340 MeV

######################## Alpha beam ####################

# Mono alpha Beam
#/gps/particle alpha
#/gps/ene/mono 2 MeV

# ==================== Run settings ===================

/run/printProgress 100